# on:
#   push:
#     tags:
#       - "v*"
# jobs:
#   package:
#     strategy:
#       matrix:
#         go-version: [1.18]
#         os: [macos-latest, windows-latest]
#     runs-on: ${{ matrix.os }}
#     steps:
#       - name: Install Go
#         uses: actions/setup-go@v2
#         with:
#           go-version: ${{ matrix.go-version }}
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Set Version
#         run: echo "VERSION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
#       - name: Get Wails
#         run: go install github.com/wailsapp/wails/cmd/wails
#       - name: Build package macOS
#         run: |
#           export PATH=${PATH}:`go env GOPATH`/bin
#           echo "building on ${{ matrix.os }}"
#           mkdir -p ~/.wails
#           cp wails.json ~/.wails/
#           export LOG_LEVEL=debug
#           export GODEBUG=1
#           wails build -p
#           echo "converting .app into a .dmg"
#           npm install -g appdmg
#           appdmg build/darwin/dmg-spec.json ExcelMate.dmg
#           zip ExcelMate.zip ExcelMate.dmg
#         if: matrix.os == 'macos-latest'
#       - name: Build package windows
#         run: |
#           $GP = (go env GOPATH)
#           $env:path = "$env:path;$GP\bin"
#           echo "building on ${{ matrix.os }}"
#           New-Item -ItemType directory -Path "$HOME\.wails" -Force
#           Copy-Item -Path "$PWD\wails.json" -Destination "$HOME\.wails\wails.json"
#           choco install mingw
#           wails build -p
#           Compress-Archive -Path .\build\ExcelMate* -DestinationPath .\ExcelMate.zip
#         if: matrix.os == 'windows-latest'
#       - name: upload artifact macOS
#         uses: actions/upload-artifact@v1
#         with:
#           name: ExcelMate-macOS
#           path: ExcelMate.zip
#         if: matrix.os == 'macos-latest'
#       - name: upload artifact windows
#         uses: actions/upload-artifact@v1
#         with:
#           name: ExcelMate-windows
#           path: ExcelMate.zip
#         if: matrix.os == 'windows-latest'

#   release:
#     runs-on: ubuntu-latest
#     needs: package
#     steps:
#       - name: Create Release
#         id: create_release
#         uses: actions/create-release@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           tag_name: ${{ github.ref }}
#           release_name: ${{ github.ref }}
#           draft: true
#           prerelease: true
#       - name: Download macOS package
#         uses: actions/download-artifact@v1
#         with:
#           name: ExcelMate-macOS
#       - name: Upload macOS package to release
#         id: upload-macOS-release-asset
#         uses: actions/upload-release-asset@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           upload_url: ${{ steps.create_release.outputs.upload_url }}
#           asset_path: ./ExcelMate-macOS/ExcelMate.zip
#           asset_name: ExcelMate_${{ github.ref }}_macOS.zip
#           asset_content_type: application/octet-stream
#       - name: Download linux package
#         uses: actions/download-artifact@v1
#         with:
#           name: ExcelMate-linux
#       - name: Upload Linux package to release
#         id: upload-linux-release-asset
#         uses: actions/upload-release-asset@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           upload_url: ${{ steps.create_release.outputs.upload_url }}
#           asset_path: ./ExcelMate-linux/ExcelMate.tar.gz
#           asset_name: ExcelMate_${{ github.ref }}_linux_x86_64.tar.gz
#           asset_content_type: application/octet-stream
#       - name: Download windows package
#         uses: actions/download-artifact@v1
#         with:
#           name: ExcelMate-windows
#       - name: Upload Windows package to release
#         id: upload-windows-release-asset
#         uses: actions/upload-release-asset@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           upload_url: ${{ steps.create_release.outputs.upload_url }}
#           asset_path: ./ExcelMate-windows/ExcelMate.zip
#           asset_name: ExcelMate_${{ github.ref }}_windows_x86_64.zip
#           asset_content_type: application/octet-stream